// VisionAgentModelDlg.cpp: 구현 파일
//

#include "stdafx.h"
#include "VisionAgent.h"
#include "VisionAgentDlg.h"
#include "VisionAgentMachineJogDlg.h"
#include "VisionAgentMachineJogInfoDlg.h"
#include "afxdialogex.h"

// CVisionAgentMachineJogDlg 대화 상자

IMPLEMENT_DYNAMIC(CVisionAgentMachineJogDlg, CDialogEx)

CVisionAgentMachineJogDlg::CVisionAgentMachineJogDlg(CWnd* pParent /*=nullptr*/)
	: CDialogEx(IDD_VISION_AGENT_MACHINE_JOG_DIALOG, pParent)
{
	Create(IDD_VISION_AGENT_MACHINE_JOG_DIALOG, pParent);
}

CVisionAgentMachineJogDlg::~CVisionAgentMachineJogDlg()
{
}

void CVisionAgentMachineJogDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}


BEGIN_MESSAGE_MAP(CVisionAgentMachineJogDlg, CDialogEx)
	ON_WM_SHOWWINDOW()
	ON_WM_TIMER()	
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_PAPER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoPaper)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_PAPER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMovePaper)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_PAPER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusPaper)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_PAPER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusPaper)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ALL_STOP, &CVisionAgentMachineJogDlg::OnBnClickedMachineJogAllStopBtn)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GANTRY_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGantryY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GANTRY_X, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGantryX)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_CAMERA_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoCameraZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_BOX_ALIGN_CAMERA_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoBoxAlignCameraY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_LOADING_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoLoadingStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_LOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoLoader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GRIPPER_CLAMP, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGripperClamp)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GRIPPER_STRETCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGripperStretch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GRIPPER_PITCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGripperPitch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_GRIPPER_WEDGE_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoGripperWedgeZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_INSPECTION_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoInspectionStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_BACKLIGHT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoBacklight)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_UNLOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoUnloader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_MAGAZINE_LIFT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoMagazineLift)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_INFO_INKJET, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogInfoInkjet)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GANTRY_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveGantryY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GANTRY_X, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveGantryX)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_CAMERA_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveCameraZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_BOX_ALIGN_CAMERA_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveBoxAlignCameraY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_LOADING_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveLoadingStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_LOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveLoader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GRIPPER_STRETCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveGripperStretch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GRIPPER_PITCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveGripperPitch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GRIPPER_WEDGE_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveGripperWedgeZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_INSPECTION_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveInspectionStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_BACKLIGHT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveBacklight)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_UNLOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveUnloader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_MAGAZINE_LIFT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveMagazineLift)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_INKJET, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogAbsMoveInkjet)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GANTRY_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusGantryY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GANTRY_X, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusGantryX)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_CAMERA_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusCameraZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_BOX_ALIGN_CAMERA_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusBoxAlignCameraY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_LOADING_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusLoadingStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_LOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusLoader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GRIPPER_STRETCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusGripperStretch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GRIPPER_PITCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusGripperPitch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GRIPPER_WEDGE_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusGripperWedgeZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_INSPECTION_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusInspectionStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_BACKLIGHT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusBacklight)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_UNLOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusUnloader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_MAGAZINE_LIFT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusMagazineLift)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_MINUS_INKJET, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelMinusInkjet)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GANTRY_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusGantryY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GANTRY_X, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusGantryX)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_CAMERA_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusCameraZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_BOX_ALIGN_CAMERA_Y, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusBoxAlignCameraY)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_LOADING_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusLoadingStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_LOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusLoader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GRIPPER_STRETCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusGripperStretch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GRIPPER_PITCH, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusGripperPitch)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GRIPPER_WEDGE_Z, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusGripperWedgeZ)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_INSPECTION_STAGE, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusInspectionStage)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_BACKLIGHT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusBacklight)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_UNLOADER, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusUnloader)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_MAGAZINE_LIFT, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusMagazineLift)
	//ON_BN_CLICKED(IDC_BUTTON_MACHINE_JOG_REL_PLUS_INKJET, &CVisionAgentMachineJogDlg::OnBnClickedButtonMachineJogRelPlusInkjet)

	//ON_BN_CLICKED(IDC_CHECK_MACHINE_JOG_WITH_MOVE_BACKLIGHT_X, &CVisionAgentMachineJogDlg::OnBnClickedCheckMachineJogWithMoveBacklightX)
	//ON_BN_CLICKED(IDC_CHECK_MACHINE_JOG_WITH_MOVE_AOI_CAMERA, &CVisionAgentMachineJogDlg::OnBnClickedCheckMachineJogWithMoveAoiCamera)

END_MESSAGE_MAP()


// CVisionAgentMachineJogDlg 메시지 처리기
BOOL CVisionAgentMachineJogDlg::OnInitDialog()
{
	CDialogEx::OnInitDialog();

	InitCtrl();

	return TRUE;
}

void CVisionAgentMachineJogDlg::OnShowWindow(BOOL bShow, UINT nStatus)
{
	CDialogEx::OnShowWindow(bShow, nStatus);

	if (bShow == TRUE)
	{
		InitPara();

		SetTimer(1, 100, NULL);
	}
	else if (bShow == FALSE)
	{
		KillTimer(1);
	}
}


void CVisionAgentMachineJogDlg::InitCtrl()
{
	m_bDialog_Entry = TRUE;


#pragma region //Combo Axis

	/*
	m_checkWithMoveBackLightX.SubclassDlgItem(IDC_CHECK_MACHINE_JOG_WITH_MOVE_BACKLIGHT_X, this);
	m_checkWithMoveAOICamera.SubclassDlgItem(IDC_CHECK_MACHINE_JOG_WITH_MOVE_AOI_CAMERA, this);

	m_ComboAxis[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GANTRY_Y, this);
	m_ComboAxis[MACHINE_JOG_GANTRY_X].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GANTRY_X, this);
	m_ComboAxis[MACHINE_JOG_CAMERA_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_CAMERA_Z, this);
	m_ComboAxis[MACHINE_JOG_LOADING_STAGE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_LOADING_STAGE, this);
	m_ComboAxis[MACHINE_JOG_LOADER].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_LOADER, this);
	m_ComboAxis[MACHINE_JOG_GRIPPER_STRETCH].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GRIPPER_STRETCH, this);
	m_ComboAxis[MACHINE_JOG_GRIPPER_WEDGE_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GRIPPER_WEDGE_Z, this);
	m_ComboAxis[MACHINE_JOG_INSPECTION_STAGE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_INSPECTION_STAGE, this);
	m_ComboAxis[MACHINE_JOG_BACKLIGHT].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_BACKLIGHT, this);
	m_ComboAxis[MACHINE_JOG_PAPER].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_PAPER, this);
	m_ComboAxis[MACHINE_JOG_UNLOADER].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_UNLOADER, this);
	m_ComboAxis[MACHINE_JOG_MAGAZINE_LIFT].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_MAGAZINE_LIFT, this);
	*/

	m_ComboAxis[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_WORKSTAGE, this);
	m_ComboAxis[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GANTRY_Y, this);
	m_ComboAxis[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GANTRY_Z, this);
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_FRAME_UPDOWN, this);
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_STAGE_UVW, this);
	m_ComboAxis[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_POPUP_Z, this);
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_FRAME_GRIPPER_SSIDE, this);
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_FRAME_GRIPPER_LSIDE, this);
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_RELEASE_SSIDE, this);
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_RELEASE_SMOVE, this);
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_RELEASE_LSIDE, this);
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_RELEASE_LMOVE, this);
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_FRAME_TRANSFER_MOVE, this);
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_ROLLER_RELEASE_MOVE, this);
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_GLASS_RELEASE_LSIDE_R, this);
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_ROLLER_RELEASE, this);
	m_ComboAxis[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_CLEANNING, this);
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_FRAME_TRANSFER_L, this);


	m_ComboAxis[MACHINE_JOG_WORKSTAGE].ResetContent();
	m_ComboAxis[MACHINE_JOG_WORKSTAGE].AddString(_T("X"));
	m_ComboAxis[MACHINE_JOG_WORKSTAGE].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GANTRY_Y].ResetContent();
	m_ComboAxis[MACHINE_JOG_GANTRY_Y].AddString(_T("Gantry Y1"));
	m_ComboAxis[MACHINE_JOG_GANTRY_Y].AddString(_T("Gantry Y2"));
	m_ComboAxis[MACHINE_JOG_GANTRY_Y].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GANTRY_Z].ResetContent();
	m_ComboAxis[MACHINE_JOG_GANTRY_Z].AddString(_T("Gantry Z1"));
	m_ComboAxis[MACHINE_JOG_GANTRY_Z].AddString(_T("Gantry Z2"));
	m_ComboAxis[MACHINE_JOG_GANTRY_Z].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].ResetContent();
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].AddString(_T("Z1"));
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].AddString(_T("Z2"));
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].AddString(_T("Z3"));
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].AddString(_T("Z4"));
	m_ComboAxis[MACHINE_JOG_FRAME_UPDOWN].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_STAGE_UVW].ResetContent();
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].AddString(_T("Y1"));
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].AddString(_T("Y2"));
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].AddString(_T("X1"));
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].AddString(_T("X2"));
	m_ComboAxis[MACHINE_JOG_STAGE_UVW].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GLASS_POPUP_Z].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_POPUP_Z].AddString(_T("Z"));
	m_ComboAxis[MACHINE_JOG_GLASS_POPUP_Z].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_SSIDE].ResetContent();
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_SSIDE].AddString(_T("L"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_SSIDE].AddString(_T("R"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].ResetContent();
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].AddString(_T("L1"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].AddString(_T("L2"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].AddString(_T("R1"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].AddString(_T("R2"));
	m_ComboAxis[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].AddString(_T("Z1"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].AddString(_T("Z2"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].AddString(_T("Z3"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].AddString(_T("Z4"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].AddString(_T("Z5"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SSIDE].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SMOVE].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SMOVE].AddString(_T("L"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SMOVE].AddString(_T("R"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_SMOVE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z1"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z2"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z3"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z4"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z5"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z6"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z7"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].AddString(_T("L_Z8"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE].SetCurSel(0);

	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].AddString(_T("L_1"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].AddString(_T("L_2"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].AddString(_T("R_1"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].AddString(_T("R_2"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LMOVE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_MOVE].ResetContent();
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_MOVE].AddString(_T("X1"));
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_MOVE].AddString(_T("X2"));
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_MOVE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].ResetContent();
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].AddString(_T("F_L"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].AddString(_T("F_R"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].AddString(_T("R_L"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].AddString(_T("R_R"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE_MOVE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].ResetContent();
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z1"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z2"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z3"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z4"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z5"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z6"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z7"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].AddString(_T("R_Z8"));
	m_ComboAxis[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].ResetContent();
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].AddString(_T("FL_Z"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].AddString(_T("FR_Z"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].AddString(_T("RL_Z"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].AddString(_T("RR_Z"));
	m_ComboAxis[MACHINE_JOG_ROLLER_RELEASE].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_CLEANNING].ResetContent();
	m_ComboAxis[MACHINE_JOG_CLEANNING].AddString(_T("Z1"));
	m_ComboAxis[MACHINE_JOG_CLEANNING].AddString(_T("Z2"));
	m_ComboAxis[MACHINE_JOG_CLEANNING].SetCurSel(0);


	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_L].ResetContent();
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_L].AddString(_T("L"));
	m_ComboAxis[MACHINE_JOG_FRAME_TRANSFER_L].SetCurSel(0);





#pragma endregion

	//Button JogInfo
	m_btnJogInfo[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_WORKSTAGE, this);
	m_btnJogInfo[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GANTRY_Y, this);
	m_btnJogInfo[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GANTRY_Z, this);
	m_btnJogInfo[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_FRAME_UPDOWN, this);
	m_btnJogInfo[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_STAGE_UVW, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_POPUP_Z, this);
	m_btnJogInfo[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_FRAME_GRIPPER_SSIDE, this);
	m_btnJogInfo[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_FRAME_GRIPPER_LSIDE, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_RELEASE_SSIDE, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_RELEASE_SMOVE, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_RELEASE_LSIDE, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_RELEASE_LMOVE, this);
	m_btnJogInfo[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_FRAME_TRANSFER_MOVE, this);
	m_btnJogInfo[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_ROLLER_RELEASE_MOVE, this);
	m_btnJogInfo[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_GLASS_RELEASE_LSIDE_R, this);
	m_btnJogInfo[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_ROLLER_RELEASE, this);
	m_btnJogInfo[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_CLEANNING, this);
	m_btnJogInfo[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_INFO_FRAME_TRANSFER_L, this);


	//Button Jog Minus
	m_btnJogMinus[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_WORKSTAGE, this);
	m_btnJogMinus[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GANTRY_Y, this);
	m_btnJogMinus[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GANTRY_Z, this);
	m_btnJogMinus[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_FRAME_UPDOWN, this);
	m_btnJogMinus[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_STAGE_UVW, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_POPUP_Z, this);
	m_btnJogMinus[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_FRAME_GRIPPER_SSIDE, this);
	m_btnJogMinus[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_FRAME_GRIPPER_LSIDE, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_RELEASE_SSIDE, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_RELEASE_SMOVE, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_RELEASE_LSIDE, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_RELEASE_LMOVE, this);
	m_btnJogMinus[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_FRAME_TRANSFER_MOVE, this);
	m_btnJogMinus[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_ROLLER_RELEASE_MOVE, this);
	m_btnJogMinus[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_GLASS_RELEASE_LSIDE_R, this);
	m_btnJogMinus[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_ROLLER_RELEASE, this);
	m_btnJogMinus[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_CLEANNING, this);
	m_btnJogMinus[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_MINUS_FRAME_TRANSFER_L, this);

	
	//Button Jog Plus
	m_btnJogPlus[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_WORKSTAGE, this);
	m_btnJogPlus[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GANTRY_Y, this);
	m_btnJogPlus[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GANTRY_Z, this);
	m_btnJogPlus[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_FRAME_UPDOWN, this);
	m_btnJogPlus[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_STAGE_UVW, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_POPUP_Z, this);
	m_btnJogPlus[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_FRAME_GRIPPER_SSIDE, this);
	m_btnJogPlus[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_FRAME_GRIPPER_LSIDE, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_RELEASE_SSIDE, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_RELEASE_SMOVE, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_RELEASE_LSIDE, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_RELEASE_LMOVE, this);
	m_btnJogPlus[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_FRAME_TRANSFER_MOVE, this);
	m_btnJogPlus[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_ROLLER_RELEASE_MOVE, this);
	m_btnJogPlus[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_GLASS_RELEASE_LSIDE_R, this);
	m_btnJogPlus[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_ROLLER_RELEASE, this);
	m_btnJogPlus[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_CLEANNING, this);
	m_btnJogPlus[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_PLUS_FRAME_TRANSFER_L, this);


	//Cur Pos
	m_stcCurPos[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_WORKSTAGE, this);
	m_stcCurPos[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GANTRY_Y, this);
	m_stcCurPos[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GANTRY_Z, this);
	m_stcCurPos[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_FRAME_UPDOWN, this);
	m_stcCurPos[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_STAGE_UVW, this);
	m_stcCurPos[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_POPUP_Z, this);
	m_stcCurPos[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_FRAME_GRIPPER_SSIDE, this);
	m_stcCurPos[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_FRAME_GRIPPER_LSIDE, this);
	m_stcCurPos[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_RELEASE_SSIDE, this);
	m_stcCurPos[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_RELEASE_SMOVE, this);
	m_stcCurPos[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_RELEASE_LSIDE, this);
	m_stcCurPos[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_RELEASE_LMOVE, this);
	m_stcCurPos[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_FRAME_TRANSFER_MOVE, this);
	m_stcCurPos[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_ROLLER_RELEASE_MOVE, this);
	m_stcCurPos[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_GLASS_RELEASE_LSIDE_R, this);
	m_stcCurPos[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_ROLLER_RELEASE, this);
	m_stcCurPos[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_CLEANNING, this);
	m_stcCurPos[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_CUR_POS_FRAME_TRANSFER_L, this);

	
	//Servo On Status
	m_stcServoOnLed[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_WORKSTAGE, this);
	m_stcServoOnLed[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GANTRY_Y, this);
	m_stcServoOnLed[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GANTRY_Z, this);
	m_stcServoOnLed[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_FRAME_UPDOWN, this);
	m_stcServoOnLed[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_STAGE_UVW, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_POPUP_Z, this);
	m_stcServoOnLed[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_FRAME_GRIPPER_SSIDE, this);
	m_stcServoOnLed[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_FRAME_GRIPPER_LSIDE, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_RELEASE_SSIDE, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_RELEASE_SMOVE, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_RELEASE_LSIDE, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_RELEASE_LMOVE, this);
	m_stcServoOnLed[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_FRAME_TRANSFER_MOVE, this);
	m_stcServoOnLed[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_ROLLER_RELEASE_MOVE, this);
	m_stcServoOnLed[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_GLASS_RELEASE_LSIDE_R, this);
	m_stcServoOnLed[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_ROLLER_RELEASE, this);
	m_stcServoOnLed[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_CLEANNING, this);
	m_stcServoOnLed[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_STATIC_MACHINE_JOG_SERVO_ON_LED_FRAME_TRANSFER_L, this);

	//Edit Abs Move Pos
	m_EditAbsMovePos[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_WORKSTAGE, this);
	m_EditAbsMovePos[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GANTRY_Y, this);
	m_EditAbsMovePos[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GANTRY_Z, this);
	m_EditAbsMovePos[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_FRAME_UPDOWN, this);
	m_EditAbsMovePos[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_STAGE_UVW, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_POPUP_Z, this);
	m_EditAbsMovePos[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_FRAME_GRIPPER_SSIDE, this);
	m_EditAbsMovePos[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_FRAME_GRIPPER_LSIDE, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_RELEASE_SSIDE, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_RELEASE_SMOVE, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_RELEASE_LSIDE, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_RELEASE_LMOVE, this);
	m_EditAbsMovePos[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_FRAME_TRANSFER_MOVE, this);
	m_EditAbsMovePos[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_ROLLER_RELEASE_MOVE, this);
	m_EditAbsMovePos[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_GLASS_RELEASE_LSIDE_R, this);
	m_EditAbsMovePos[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_ROLLER_RELEASE, this);
	m_EditAbsMovePos[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_CLEANNING, this);
	m_EditAbsMovePos[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_ABS_POS_FRAME_TRANSFER_L, this);

	//Button Abs Move
	m_btnAbsMove[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_WORKSTAGE, this);
	m_btnAbsMove[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GANTRY_Y, this);
	m_btnAbsMove[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GANTRY_Z, this);
	m_btnAbsMove[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_FRAME_UPDOWN, this);
	m_btnAbsMove[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_STAGE_UVW, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_POPUP_Z, this);
	m_btnAbsMove[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_FRAME_GRIPPER_SSIDE, this);
	m_btnAbsMove[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_FRAME_GRIPPER_LSIDE, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_RELEASE_SSIDE, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_RELEASE_SMOVE, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_RELEASE_LSIDE, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_RELEASE_LMOVE, this);
	m_btnAbsMove[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_FRAME_TRANSFER_MOVE, this);
	m_btnAbsMove[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_ROLLER_RELEASE_MOVE, this);
	m_btnAbsMove[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_GLASS_RELEASE_LSIDE_R, this);
	m_btnAbsMove[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_ROLLER_RELEASE, this);
	m_btnAbsMove[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_CLEANNING, this);
	m_btnAbsMove[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_ABS_MOVE_FRAME_TRANSFER_L, this);
	
	//Edit Relative Move Distance
	m_EditRelativeDist[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_WORKSTAGE, this);
	m_EditRelativeDist[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GANTRY_Y, this);
	m_EditRelativeDist[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GANTRY_Z, this);
	m_EditRelativeDist[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_FRAME_UPDOWN, this);
	m_EditRelativeDist[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_STAGE_UVW, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_POPUP_Z, this);
	m_EditRelativeDist[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_FRAME_GRIPPER_SSIDE, this);
	m_EditRelativeDist[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_FRAME_GRIPPER_LSIDE, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_RELEASE_SSIDE, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_RELEASE_SMOVE, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_RELEASE_LSIDE, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_RELEASE_LMOVE, this);
	m_EditRelativeDist[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_FRAME_TRANSFER_MOVE, this);
	m_EditRelativeDist[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_ROLLER_RELEASE_MOVE, this);
	m_EditRelativeDist[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_GLASS_RELEASE_LSIDE_R, this);
	m_EditRelativeDist[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_ROLLER_RELEASE, this);
	m_EditRelativeDist[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_CLEANNING, this);
	m_EditRelativeDist[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_EDIT_MACHINE_JOG_REL_DIST_FRAME_TRANSFER_L, this);

	//Button Relative Move Minus
	m_btnRelMinus[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_WORKSTAGE, this);
	m_btnRelMinus[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GANTRY_Y, this);
	m_btnRelMinus[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GANTRY_Z, this);
	m_btnRelMinus[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_FRAME_UPDOWN, this);
	m_btnRelMinus[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_STAGE_UVW, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_POPUP_Z, this);
	m_btnRelMinus[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_FRAME_GRIPPER_SSIDE, this);
	m_btnRelMinus[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_FRAME_GRIPPER_LSIDE, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_RELEASE_SSIDE, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_RELEASE_SMOVE, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_RELEASE_LSIDE, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_RELEASE_LMOVE, this);
	m_btnRelMinus[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_FRAME_TRANSFER_MOVE, this);
	m_btnRelMinus[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_ROLLER_RELEASE_MOVE, this);
	m_btnRelMinus[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_GLASS_RELEASE_LSIDE_R, this);
	m_btnRelMinus[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_ROLLER_RELEASE, this);
	m_btnRelMinus[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_CLEANNING, this);
	m_btnRelMinus[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_MINUS_FRAME_TRANSFER_L, this);

	//Button Relative Move Plus
	m_btnRelPlus[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_WORKSTAGE, this);
	m_btnRelPlus[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GANTRY_Y, this);
	m_btnRelPlus[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GANTRY_Z, this);
	m_btnRelPlus[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_FRAME_UPDOWN, this);
	m_btnRelPlus[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_STAGE_UVW, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_POPUP_Z, this);
	m_btnRelPlus[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_FRAME_GRIPPER_SSIDE, this);
	m_btnRelPlus[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_FRAME_GRIPPER_LSIDE, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_RELEASE_SSIDE, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_RELEASE_SMOVE, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_RELEASE_LSIDE, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_RELEASE_LMOVE, this);
	m_btnRelPlus[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_FRAME_TRANSFER_MOVE, this);
	m_btnRelPlus[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_ROLLER_RELEASE_MOVE, this);
	m_btnRelPlus[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_GLASS_RELEASE_LSIDE_R, this);
	m_btnRelPlus[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_ROLLER_RELEASE, this);
	m_btnRelPlus[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_CLEANNING, this);
	m_btnRelPlus[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_BUTTON_MACHINE_JOG_REL_PLUS_FRAME_TRANSFER_L, this);

	//Combo Jog Speed
	m_ComboManualSpeed[MACHINE_JOG_WORKSTAGE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_WORKSTAGE, this);
	m_ComboManualSpeed[MACHINE_JOG_GANTRY_Y].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GANTRY_Y, this);
	m_ComboManualSpeed[MACHINE_JOG_GANTRY_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GANTRY_Z, this);
	m_ComboManualSpeed[MACHINE_JOG_FRAME_UPDOWN].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_FRAME_UPDOWN, this);
	m_ComboManualSpeed[MACHINE_JOG_STAGE_UVW].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_STAGE_UVW, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_POPUP_Z].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_POPUP_Z, this);
	m_ComboManualSpeed[MACHINE_JOG_FRAME_GRIPPER_SSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_FRAME_GRIPPER_SSIDE, this);
	m_ComboManualSpeed[MACHINE_JOG_FRAME_GRIPPER_LSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_FRAME_GRIPPER_LSIDE, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_RELEASE_SSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_RELEASE_SSIDE, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_RELEASE_SMOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_RELEASE_SMOVE, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_RELEASE_LSIDE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_RELEASE_LSIDE, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_RELEASE_LMOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_RELEASE_LMOVE, this);
	m_ComboManualSpeed[MACHINE_JOG_FRAME_TRANSFER_MOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_FRAME_TRANSFER_MOVE, this);
	m_ComboManualSpeed[MACHINE_JOG_ROLLER_RELEASE_MOVE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_ROLLER_RELEASE_MOVE, this);
	m_ComboManualSpeed[MACHINE_JOG_GLASS_RELEASE_LSIDE_R].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_GLASS_RELEASE_LSIDE_R, this);
	m_ComboManualSpeed[MACHINE_JOG_ROLLER_RELEASE].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_ROLLER_RELEASE, this);
	m_ComboManualSpeed[MACHINE_JOG_CLEANNING].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_CLEANNING, this);
	m_ComboManualSpeed[MACHINE_JOG_FRAME_TRANSFER_L].SubclassDlgItem(IDC_COMBO_MACHINE_JOG_SPEED_FRAME_TRANSFER_L, this);




	int i = 0;
	for (i = 0; i < MACHINE_JOG_MAX; i++)
	{
		m_btnJogInfo[i].SetColor(BLACK, LLTGRAY);
		m_btnJogMinus[i].SetColor(BLACK, LLTGRAY);
		m_btnJogPlus[i].SetColor(BLACK, LLTGRAY);

		m_stcCurPos[i].SetBackgroundColor(DKCYAN);
		m_stcCurPos[i].SetTextColor(BLACK);

		m_stcServoOnLed[i].SetBackgroundColor(LLTGRAY);
		m_stcServoOnLed[i].SetTextColor(BLACK);

		m_btnAbsMove[i].SetColor(BLACK, LLTGRAY);
		m_btnRelMinus[i].SetColor(BLACK, LLTGRAY);
		m_btnRelPlus[i].SetColor(BLACK, LLTGRAY);

		m_ComboManualSpeed[i].ResetContent();
		m_ComboManualSpeed[i].AddString(_T("LOW"));
		m_ComboManualSpeed[i].AddString(_T("MEDIUM"));
		m_ComboManualSpeed[i].AddString(_T("HIGH"));
		m_ComboManualSpeed[i].SetCurSel(1);
	}
}

void CVisionAgentMachineJogDlg::InitPara()
{
	m_JogMotion = &Devs::m_JogMotion;
	//SharedInfo::m_eAxisJog = AXIS_NONE;


	/*
	m_checkWithMoveBackLightX.SetCheck(m_JogMotion->m_nWithMoveBackLightX);
	m_checkWithMoveAOICamera.SetCheck(m_JogMotion->m_bWithMoveAOICameraX);
	*/

	int i = 0;
	for (i = 0; i < MACHINE_JOG_MAX; i++)
	{
		m_EditAbsMovePos[i].SetWindowText(_T("0.0"));
		m_EditRelativeDist[i].SetWindowText(_T("0.0"));
	}
}

BOOL CVisionAgentMachineJogDlg::PreTranslateMessage(MSG* pMsg)
{
	CVisionAgentDlg *pVisionAgentDlg;
	pVisionAgentDlg = (CVisionAgentDlg *)theApp.m_pMainWnd;

	CString StrDiscription = _T("");
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0., dAccel = 0.0, dDecel = 0.0;
	int i = 0;

	switch (pMsg->message)
	{
	case WM_LBUTTONDOWN:
	{
/*
		for (i = 0; i < MACHINE_JOG_MAX; i++)
		{
			if (pMsg->hwnd == m_btnJogMinus[i].GetSafeHwnd())
			{
				if (!GetAxisJogParamByUI((en_MACHINE_JOG_DEF)i, &SharedInfo::m_eAxisJog, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription)) break;

				if (i == MACHINE_JOG_GANTRY_X)
					m_JogMotion->JogMove(SharedInfo::m_eAxisJog, -dJogSpeed, dAccel, dDecel, 0);
				else
					m_JogMotion->JogMove(SharedInfo::m_eAxisJog, -dJogSpeed, dAccel, dDecel);
				//Total_Msg(_T("Jog Start Minus"));
				break;
			}
			else if (pMsg->hwnd == m_btnJogPlus[i].GetSafeHwnd())
			{
				if (!GetAxisJogParamByUI((en_MACHINE_JOG_DEF)i, &SharedInfo::m_eAxisJog, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription)) break;

				if (i == MACHINE_JOG_GANTRY_X)
					m_JogMotion->JogMove(SharedInfo::m_eAxisJog, dJogSpeed, dAccel, dDecel, 0);
				else
					m_JogMotion->JogMove(SharedInfo::m_eAxisJog, dJogSpeed, dAccel, dDecel);
				//Total_Msg(_T("Jog Start Plus"));
				break;
			}
		}
*/
		break;
	}
	case WM_LBUTTONUP:
	{
/*
		for (i = 0; i < MACHINE_JOG_MAX; i++)
		{
			if (pMsg->hwnd == m_btnJogMinus[i].GetSafeHwnd() && SharedInfo::m_eAxisJog != AXIS_NONE)
			{
				if (i == MACHINE_JOG_GANTRY_X)
					m_JogMotion->JogStop(SharedInfo::m_eAxisJog, 0);
				else
					m_JogMotion->JogStop(SharedInfo::m_eAxisJog);

				SharedInfo::m_eAxisJog = AXIS_NONE;
				Total_Msg(_T("Jog Stop Minus"));
				break;
			}
			else if (pMsg->hwnd == m_btnJogPlus[i].GetSafeHwnd() && SharedInfo::m_eAxisJog != AXIS_NONE)
			{
				if (i == MACHINE_JOG_GANTRY_X)
					m_JogMotion->JogStop(SharedInfo::m_eAxisJog, 0);
				else
					m_JogMotion->JogStop(SharedInfo::m_eAxisJog);

				SharedInfo::m_eAxisJog = AXIS_NONE;
				Total_Msg(_T("Jog Stop Plus"));
				break;
			}
		}
		break;
		*/
	}
	}
	return CDialogEx::PreTranslateMessage(pMsg);
}

void CVisionAgentMachineJogDlg::OnTimer(UINT_PTR nIDEvent)
{
	CVisionAgentDlg *pVisionAgentDlg = (CVisionAgentDlg*)theApp.m_pMainWnd;
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0.0, dAccel = 0.0, dDecel = 0.0;
	enum_Axis eAxis = AXIS_NONE;
	CString StrDiscription = _T(""), Str = _T("");

	if (nIDEvent == 1)
	{
		if (IsWindowVisible())
		{
			for (int i = 0; i < MACHINE_JOG_MAX; i++)
			{
				if (!GetAxisJogParamByUI((en_MACHINE_JOG_DEF)i, &eAxis, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription))
					continue;

				if (eAxis == AXIS_GANTRY_Y1)
				{
					Str.Format(_T("%.5f"), SharedInfo::GetActPos(eAxis));
				}
				else
				{
					Str.Format(_T("%.5f"), SharedInfo::GetCmdPos(eAxis));
				}

				m_stcCurPos[i].SetData(Str);
			}
		}
	}

	CDialogEx::OnTimer(nIDEvent);
}


void CVisionAgentMachineJogDlg::OnBnClickedMachineJogAllStopBtn()
{
	m_JogMotion->StopAll();
	Etc_Msg(_T("[MachineJog] All Stop Button Click"));
}


void CVisionAgentMachineJogDlg::JogMoveComplete(void * argument)
{
	int a = 0;
	a = 1;
}

#pragma region //JogInfo


#pragma endregion

#pragma region //Common Function
BOOL CVisionAgentMachineJogDlg::GetAxisJogParamByUI(en_MACHINE_JOG_DEF eJogUIDefine, enum_Axis* pnAxis, double* pPosAbs, double* pPosRel, double* pJogSpeed, double* pAccel, double* pDecel, CString* strDiscription)
{
	CVisionAgentDlg *pVisionAgentDlg;
	pVisionAgentDlg = (CVisionAgentDlg *)theApp.m_pMainWnd;

	BOOL bResult = TRUE;
	enum_Axis eAxis = AXIS_NONE;
	CString strPosAbs, strPosRel;
	int nSelAxis = -1, nSelManualSpeed = -1;
	double dPosAbs = 0.0, dPosRel = 0.0, dManualVel = 0.0, dManualAccel = 0.0, dManualDecel = 0.0;

	nSelAxis = m_ComboAxis[eJogUIDefine].GetCurSel();
	nSelManualSpeed = m_ComboManualSpeed[eJogUIDefine].GetCurSel();
	m_EditAbsMovePos[eJogUIDefine].GetWindowText(strPosAbs);
	m_EditRelativeDist[eJogUIDefine].GetWindowText(strPosRel);

	dPosAbs = _wtof(strPosAbs);
	dPosRel = _wtof(strPosRel);

	if (eJogUIDefine == MACHINE_JOG_GANTRY_Y)
	{
		switch (nSelAxis)
		{
		case 0: eAxis = AXIS_GANTRY_Y1; *strDiscription = _T("Virtual Gantry Y");  break;
		default: bResult = FALSE; break;
		}
	}
	else
	{
		return FALSE;
	}

	if (bResult == TRUE)
	{
		enum_Axis eAxisTemp = eAxis;

		SharedInfo::GetManualSpeed(eAxisTemp, (enum_AXIS_SPEED)nSelManualSpeed, &dManualVel, &dManualAccel, &dManualDecel);

		*pnAxis = eAxis;
		*pPosAbs = dPosAbs;
		*pPosRel = dPosRel;
		*pJogSpeed = dManualVel;
		*pAccel = dManualAccel;
		*pDecel = dManualDecel;
	}
	
	return bResult;
}

void CVisionAgentMachineJogDlg::funcJogInfo(en_MACHINE_JOG_DEF eJogUIDefine)
{
	CString StrDiscription = _T(""), Str = _T("");
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0.0, dAccel = 0.0, dDecel = 0.0;
	enum_Axis eAxis = AXIS_NONE;

	if (!GetAxisJogParamByUI(eJogUIDefine, &eAxis, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription))
		return;

	CVisionAgentMachineJogInfoDlg JogInfoDlg;
	JogInfoDlg.m_eAxis = eAxis;
	JogInfoDlg.m_strAxis = StrDiscription;
	JogInfoDlg.DoModal();
}
void CVisionAgentMachineJogDlg::funcAbsMove(en_MACHINE_JOG_DEF eJogUIDefine)
{
	CString StrDiscription = _T(""), Str = _T("");
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0.0, dAccel = 0.0, dDecel = 0.0;
	enum_Axis eAxis = AXIS_NONE;
	int nAxisType = -1; // 0 DirectAjin, 1:RemoteUmac, 2:RemoteAjin
	int nAxisNo = -1;
	double dPosXTemp = 0.0, dPosYTemp = 0.0;

	if (!GetAxisJogParamByUI(eJogUIDefine, &eAxis, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription))
		return;

#if 1
#pragma region
	if (CModelData::m_InspectionPara.Info.bMappingDataUse)
	{
		double dPosPrevX = 0.0, dPosPrevY = 0.0, dPosMapX = 0.0, dPosMapY = 0.0;
		if (eAxis == AXIS_GANTRY_X)
		{
			dPosPrevX = dPosMapX = dPosAbs;
			dPosPrevY = dPosMapY = SharedInfo::GetActPos(AXIS_GANTRY_Y1);
			Devs::m_MappingProc.GetGlassMapping_CalibPosXY(eMAPPING_ID_10X, &dPosAbs, &dPosMapY);
			Str.Format(_T("Mapping Data X:%.5f, Y:%.5f => X:%.5f, Y:%.5f"), dPosPrevX, dPosPrevY, dPosAbs, dPosMapY);
			Total_Msg(Str);
		}
		else if(eAxis == AXIS_GANTRY_Y1)
		{
			dPosPrevX = dPosMapX = SharedInfo::GetCmdPos(AXIS_GANTRY_X);
			dPosPrevY = dPosMapY = dPosAbs;
			Devs::m_MappingProc.GetGlassMapping_CalibPosXY(eMAPPING_ID_10X, &dPosXTemp, &dPosAbs);
			Str.Format(_T("Mapping Data X:%.5f, Y:%.5f => X:%.5f, Y:%.5f"), dPosPrevX, dPosPrevY, dPosMapX, dPosAbs);
			Total_Msg(Str);
		}
	}
#pragma endregion
#endif

	if (eAxis == AXIS_GANTRY_X && m_JogMotion->m_nWithMoveBackLightX == 1)
	{
		if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
		{
			Str.Format(_T("%s Servo Off !!"), StrDiscription);
			AfxMessageBox(Str);
			return;
		}
	}
	else if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
	{
		Str.Format(_T("%s Servo Off !!"), StrDiscription);
		AfxMessageBox(Str);
		return;
	}

	Str.Format(_T("%s Abs Move To Pos: %.5f Start?"), StrDiscription, dPosAbs);
	int nResult = AfxMessageBox(Str, MB_OKCANCEL);
	if (nResult == IDOK)
	{
		if (eAxis == AXIS_GANTRY_X)
		{
			double dBackLightOffset = CSystemData::m_Coordinate.Info.dOffsetReview10xToAoi_X;
			if (m_JogMotion->m_bWithMoveAOICameraX == TRUE)
			{
				m_JogMotion->AbsMove(eAxis, dPosAbs, dJogSpeed, dAccel, dDecel, m_JogMotion->m_nWithMoveBackLightX, dBackLightOffset);
				if (m_JogMotion->m_nWithMoveBackLightX)
					Str.Format(_T("Gantry X Abs Move (TargetPos:%.5f, Vel:%.1f, Accel:%.1f, Decel:%.1f, BackLightX:%.5f"), dPosAbs, dJogSpeed, dAccel, dDecel, dPosAbs + dBackLightOffset);
				else
					Str.Format(_T("Gantry X Abs Move (TargetPos:%.5f, Vel:%.1f, Accel:%.1f, Decel:%.1f"), dPosAbs, dJogSpeed, dAccel, dDecel);
			}
			else
			{
				m_JogMotion->AbsMove(eAxis, dPosAbs, dJogSpeed, dAccel, dDecel, m_JogMotion->m_nWithMoveBackLightX);
				if (m_JogMotion->m_nWithMoveBackLightX)
					Str.Format(_T("Gantry X Abs Move (TargetPos:%.5f, Vel:%.1f, Accel:%.1f, Decel:%.1f, BackLightX:%.5f"), dPosAbs, dJogSpeed, dAccel, dDecel, dPosAbs);
				else
					Str.Format(_T("Gantry X Abs Move (TargetPos:%.5f, Vel:%.1f, Accel:%.1f, Decel:%.1f"), dPosAbs, dJogSpeed, dAccel, dDecel);
			}
		}
		else
		{
			m_JogMotion->AbsMove(eAxis, dPosAbs, dJogSpeed, dAccel, dDecel);
			Str.Format(_T("%s Abs Move (TargetPos:%.5f, Vel:%.1f, Accel:%.1f, Decel:%.1f"), StrDiscription, dPosAbs, dJogSpeed, dAccel, dDecel);
		}
		Total_Msg(Str);
	}
}

void CVisionAgentMachineJogDlg::funcRelMoveMinus(en_MACHINE_JOG_DEF eJogUIDefine)
{
	CString StrDiscription = _T(""), Str = _T("");
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0.0, dAccel = 0.0, dDecel = 0.0;
	enum_Axis eAxis = AXIS_NONE;

	if (!GetAxisJogParamByUI(eJogUIDefine, &eAxis, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription))
		return;

	if (eAxis == AXIS_GANTRY_X && m_JogMotion->m_nWithMoveBackLightX == 1)
	{
		if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
		{
			Str.Format(_T("%s Servo Off !!"), StrDiscription);
			AfxMessageBox(Str);
			return;
		}
	}
	else if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
	{
		Str.Format(_T("%s Servo Off !!"), StrDiscription);
		AfxMessageBox(Str);
		return;
	}

	Str.Format(_T("%s Relative Move Dist: %.5f Start?"), StrDiscription, dPosRel); //KJT 20200812
	int nResult = AfxMessageBox(Str, MB_OKCANCEL);
	if (nResult == IDOK)
	{
		if (eAxis == AXIS_GANTRY_X)
		{
			m_JogMotion->RelMove((enum_Axis)eAxis, -dPosRel, dJogSpeed, dAccel, dDecel, m_JogMotion->m_nWithMoveBackLightX);
		}
		else
			m_JogMotion->RelMove((enum_Axis)eAxis, -dPosRel, dJogSpeed, dAccel, dDecel);
	}
}
void CVisionAgentMachineJogDlg::funcRelMovePlus(en_MACHINE_JOG_DEF eJogUIDefine)
{
	CString StrDiscription = _T(""), Str = _T("");
	double	dPosAbs = 0.0, dPosRel = 0.0, dJogSpeed = 0.0, dAccel = 0.0, dDecel = 0.0;
	enum_Axis eAxis = AXIS_NONE;

	if (!GetAxisJogParamByUI(eJogUIDefine, &eAxis, &dPosAbs, &dPosRel, &dJogSpeed, &dAccel, &dDecel, &StrDiscription))
		return;

	if (eAxis == AXIS_GANTRY_X && m_JogMotion->m_nWithMoveBackLightX == 1)
	{
		if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
		{
			Str.Format(_T("%s Servo Off !!"), StrDiscription);
			AfxMessageBox(Str);
			return;
		}
	}
	else if (SharedInfo::GetServoOnStatus(eAxis) == FALSE)
	{
		Str.Format(_T("%s Servo Off !!"), StrDiscription);
		AfxMessageBox(Str);
		return;
	}

	Str.Format(_T("%s Relative Move Dist: %.5f Start?"), StrDiscription, dPosRel); //KJT 20200812
	int nResult = AfxMessageBox(Str, MB_OKCANCEL);
	if (nResult == IDOK)
	{
		if (eAxis == AXIS_GANTRY_X)
		{
			m_JogMotion->RelMove(eAxis, dPosRel, dJogSpeed, dAccel, dDecel, m_JogMotion->m_nWithMoveBackLightX);
		}
		else
			m_JogMotion->RelMove(eAxis, dPosRel, dJogSpeed, dAccel, dDecel);

		Str.Format(_T("%s RelMove Plus %.5f"), StrDiscription, dPosRel);
		Total_Msg(Str);
	}
}
#pragma endregion

void CVisionAgentMachineJogDlg::OnBnClickedCheckMachineJogWithMoveBacklightX()
{
	CString Str = _T("");

	m_JogMotion->m_nWithMoveBackLightX = 1 - m_JogMotion->m_nWithMoveBackLightX;

	m_checkWithMoveBackLightX.SetCheck(m_JogMotion->m_nWithMoveBackLightX);

	Str.Format(_T("Check WithMoveBackLightX %d"), m_JogMotion->m_nWithMoveBackLightX);
	Total_Msg(Str);
}


void CVisionAgentMachineJogDlg::OnBnClickedCheckMachineJogWithMoveAoiCamera()
{
	CString Str = _T("");

	m_JogMotion->m_bWithMoveAOICameraX = !m_JogMotion->m_bWithMoveAOICameraX;

	m_checkWithMoveAOICamera.SetCheck(m_JogMotion->m_bWithMoveAOICameraX);

	Str.Format(_T("Check WithMoveAOICameraX %d"), m_JogMotion->m_bWithMoveAOICameraX);
	Total_Msg(Str);
}



