#pragma once

class CAutoRunFlow : public CBaseFlow
{
public:
	CAutoRunFlow();
	~CAutoRunFlow();

private:
	BOOL			m_FlowFinish;

	void(*m_StateComplete)(void *pArgument);

	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);

public:
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;

	BOOL InitProcess();
	BOOL EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			Is_FlowDone() { return m_bFlowDone; }

	BOOL			Start();
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329
	CTime m_timeCycleStart; //KJT 20210415

	enum eAutoRunFlow
	{
		_eAUTO_RUN_FLOW_ERROR = -1,

		_eAUTO_RUN_FLOW_IDLE = 0,
		_eAUTO_RUN_FLOW_START,

		_eAUTO_RUN_FLOW_BOX_ALIGN_START,
		_eAUTO_RUN_FLOW_BOX_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_STICK_PAPER_LOAD_START,
		_eAUTO_RUN_FLOW_STICK_PAPER_LOAD_DONE_CHECK,
		_eAUTO_RUN_FLOW_STICK_PAPER_UNLOAD_START,
		_eAUTO_RUN_FLOW_STICK_PAPER_UNLOAD_DONE_CHECK,

		_eAUTO_RUN_FLOW_PRE_ALIGN_START,
		_eAUTO_RUN_FLOW_PRE_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_MAIN_ALIGN_START,
		_eAUTO_RUN_FLOW_MAIN_ALIGN_DONE_CHECK,
		
		//_eAUTO_RUN_FLOW_SW_ALIGN_START, //KJT 20210314
		//_eAUTO_RUN_FLOW_SW_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_TP_START, //KJT 20210406
		_eAUTO_RUN_FLOW_TP_DONE_CHECK,		

		_eAUTO_RUN_FLOW_PPA_START,
		_eAUTO_RUN_FLOW_PPA_DONE_CHECK,

		//_eAUTO_RUN_FLOW_AOI_START,
		//_eAUTO_RUN_FLOW_AOI_DONE_CHECK,

		//_eAUTO_RUN_FLOW_AOI_REVIEW_START,
		//_eAUTO_RUN_FLOW_AOI_REVIEW_DONE_CHECK,

		//_eAUTO_RUN_FLOW_3D_START,
		//_eAUTO_RUN_FLOW_3D_DONE_CHECK,

		_eAUTO_RUN_FLOW_STICK_UNLOAD_IN_STAGE_TO_CST_START,
		_eAUTO_RUN_FLOW_STICK_UNLOAD_IN_STAGE_TO_CST_DONE_CHECK,

#pragma region //Tension Flow
		_eAUTO_RUN_FLOW_STICK_CLAMP_TENSION_START,
		_eAUTO_RUN_FLOW_STICK_CLAMP_TENSION_DONE_CHECK,

		_eAUTO_RUN_FLOW_PRE_TENSION_ALIGN_START,
		_eAUTO_RUN_FLOW_PRE_TENSION_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_MAIN_TENSION_ALIGN_START,
		_eAUTO_RUN_FLOW_MAIN_TENSION_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_EDGE_TENSION_ALIGN_START,
		_eAUTO_RUN_FLOW_EDGE_TENSION_ALIGN_DONE_CHECK,

		_eAUTO_RUN_FLOW_STICK_RELEASE_UNCLAMP_START,
		_eAUTO_RUN_FLOW_STICK_RELEASE_UNCLAMP_DONE_CHECK,
#pragma endregion

		_eAUTO_RUN_FLOW_SITCK_TENSION_ONCE_START, //KJT 20210406
		_eAUTO_RUN_FLOW_SITCK_TENSION_ONCE_DONE_CHECK,

		_eAUTO_RUN_FLOW_DONE,
	};
};

