#pragma once

class CMaskEdgeTenstionAlignFlow : public CBaseFlow
{
public:
	CMaskEdgeTenstionAlignFlow();
	~CMaskEdgeTenstionAlignFlow();

private:
	BOOL			m_FlowFinish;

	void(*m_StateComplete)(void *pArgument);

	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);

private:
#ifndef SIM_MODE
	wk_MilCameraInfo m_CameraInfo;
	wk_MilBlobData m_BlobData;
	stBlobResult stResult;
#endif

public:
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;

	BOOL InitProcess();
	BOOL EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	int *m_pReviewCoaxial;
	int *m_pReviewRing;
	int *m_pReviewThreshold;
	int *m_pReviewMarkFind;

#pragma region //Vision
	BOOL m_bLaserFocusUseFlag;
	BOOL m_bAutoFocusUseFlag;

	double m_AlignPointValue[2][4];
	double m_AlignVisionResultValue[2][4];

	double m_dDiffPos[3];
	double m_dTarget[3];

	int m_nAlignPoint;
#pragma endregion

#pragma region //Move Func
	double m_dTargetPosX;
	double m_dTargetPosY;

	double GetAlignPos_X(int nAlignCount);
	double GetAlignPos_Y(int nAlignCount);
	
#pragma endregion

	enum eMaskEdgeTensionAlign
	{
		_eEDGE_TENSION_ALIGN_FLOW_ERROR = -1,

		_eEDGE_TENSION_ALIGN_FLOW_IDLE = 0,
		_eEDGE_TENSION_ALIGN_FLOW_START,
		_eEDGE_TENSION_ALIGN_FLOW_INTERLOCK,

#pragma region //Unloader Ready
		_eEDGE_TENSION_ALIGN_FLOW_UNLOADER_READY,
		_eEDGE_TENSION_ALIGN_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry Z, X Ready
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_ZX_READY,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_eEDGE_TENSION_ALIGN_FLOW_LOADER_READY,
		_eEDGE_TENSION_ALIGN_FLOW_LOADER_READY_CHECK,
#pragma endregion

//#pragma region //Box Camera Ready
//		_eEDGE_TENSION_ALIGN_FLOW_BOX_CAMERA_READY,
//		_eEDGE_TENSION_ALIGN_FLOW_BOX_CAMERA_READY_CHECK,
//#pragma endregion

#pragma region //PaperUnloaderZXY Ready
		_eEDGE_TENSION_ALIGN_FLOW_PAPER_UNLOADER_ZXY_READY,
		_eEDGE_TENSION_ALIGN_FLOW_PAPER_UNLOADER_ZXY_READY_CHECK,
#pragma endregion

		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_XY_ALIGN_POS_1ST,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_XY_ALIGN_POS_1ST_CHECK,
		//_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z1_INSPECTION_POS_1ST,
		//_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z1_INSPECTION_POS_1ST_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z3_INSPECTION_POS_1ST,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z3_INSPECTION_POS_1ST_CHECK,

		//_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z1_INSPECTION_POS_2ND,
		//_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z1_INSPECTION_POS_2ND_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z3_INSPECTION_POS_2ND,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_Z3_INSPECTION_POS_2ND_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_XY_ALIGN_POS_2ND,
		_eEDGE_TENSION_ALIGN_FLOW_GANTRY_XY_ALIGN_POS_2ND_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_AUTOFOCUS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_LASER_FOCUS_START,
		_eEDGE_TENSION_ALIGN_FLOW_LASER_FOCUS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_IMAGE_FOCUS_START,
		_eEDGE_TENSION_ALIGN_FLOW_IMAGE_FOCUS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GRAB_START,
		_eEDGE_TENSION_ALIGN_FLOW_GRAB_DONE_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GRIPPER_Z_TENSTION_POS,
		_eEDGE_TENSION_ALIGN_FLOW_GRIPPER_Z_TENSTION_POS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_STRETCH_TENSTION_START,
		_eEDGE_TENSION_ALIGN_FLOW_STRETCH_TENSTION_DONE_CHECK,
		//_eEDGE_TENSION_ALIGN_FLOW_PITCH_TENSTION_START,
		//_eEDGE_TENSION_ALIGN_FLOW_PITCH_TENSTION_DONE_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_GRIPPER_Z_CLAMP_POS,
		_eEDGE_TENSION_ALIGN_FLOW_GRIPPER_Z_CLAMP_POS_CHECK,

		//_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_Z1_WAIT_POS,
		//_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_Z1_WAIT_POS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_Z3_WAIT_POS,
		_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_Z3_WAIT_POS_CHECK,
		_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_XY_WAIT_POS,
		_eEDGE_TENSION_ALIGN_FLOW_FINISH_GANTRY_XY_WAIT_POS_CHECK,

		_eEDGE_TENSION_ALIGN_FLOW_DONE,
	};
};

