#pragma once
class CPaperUnloaderZX_PaperLoadFlow : public CBaseFlow
{
public:
	CPaperUnloaderZX_PaperLoadFlow();
	~CPaperUnloaderZX_PaperLoadFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();
	
	//double			m_dTargetPosZ;
	double			m_dTargetPosZ;
	double			m_dTargetPosX;

	int				m_nGroupStepIndex; //KJT 20210221
	BOOL			m_bGroupStepDone[200]; //KJT 20210221

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	enum ePaperUnloaderZX_PaperLoad
	{
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_ERROR = -1,

		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_IDLE = 0,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_START,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_INTERLOCK,

#pragma region //1. Paper PickUp In Box
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS,	
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_VAC_ON,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS_CHECK,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS,
		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS_CHECK,
#pragma endregion //1. PickUp In Box

		_ePAPER_UNLOADER_ZX_PAPER_LOAD_FLOW_DONE,
	};
};

