#pragma once
class CPaperLoadUnloadFlow : public CBaseFlow
{
public:
	CPaperLoadUnloadFlow();
	~CPaperLoadUnloadFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(enum_CassetteFloor eTargetFloor);
	BOOL			Stop();
	
	//double			m_dTargetPosZ;
	double			m_dTargetPosZ;
	double			m_dTargetPosX;

	int				m_nGroupStepIndex; //KJT 20210221
	BOOL			m_bGroupStepDone[200]; //KJT 20210221

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	CTime m_timeStart; //KJT 20210329

	enum_CassetteFloor m_eTargetFloor;

	BOOL			FlowInterlock();

	enum ePaperLoadUnload
	{
		_ePAPER_LOAD_UNLOAD_FLOW_ERROR = -1,

		_ePAPER_LOAD_UNLOAD_FLOW_IDLE = 0,
		_ePAPER_LOAD_UNLOAD_FLOW_START,
		_ePAPER_LOAD_UNLOAD_FLOW_INTERLOCK,

#pragma region //Unloader Ready
		_ePAPER_LOAD_UNLOAD_FLOW_UNLOADER_READY,
		_ePAPER_LOAD_UNLOAD_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry Z,X Ready
		_ePAPER_LOAD_UNLOAD_FLOW_GANTRY_ZX_READY,
		_ePAPER_LOAD_UNLOAD_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_ePAPER_LOAD_UNLOAD_FLOW_LOADER_READY,
		_ePAPER_LOAD_UNLOAD_FLOW_LOADER_READY_CHECK,
#pragma endregion

#pragma region //PaperUnloader Ready
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_ZX_READY,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_ZX_READY_CHECK,
#pragma endregion

#pragma region //1. Paper PickUp In Box
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_IN_BOX_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_IN_BOX_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS,	
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_VAC_ON,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS_CHECK,
#pragma endregion //1. PickUp In Box

#pragma region //2. Paper Unload
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_UNLOAD_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_UNLOAD_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_UNLOAD_DOWN_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_UNLOAD_DOWN_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_VAC_OFF,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_VAC_OFF_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_FINISH_WAIT_POS,		
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Z_FINISH_WAIT_POS_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_FINISH_WAIT_POS,
		_ePAPER_LOAD_UNLOAD_FLOW_PAPER_UNLOADER_Y_FINISH_WAIT_POS_CHECK,
#pragma endregion //2. Paper Unload

#pragma region //Cst Move
		_ePAPER_LOAD_UNLOAD_FLOW_CST_RECV_READY_MOVE,
		_ePAPER_LOAD_UNLOAD_FLOW_CST_RECV_READY_DONE_CHECK,
		_ePAPER_LOAD_UNLOAD_FLOW_CST_RECV_DONE_MOVE,
		_ePAPER_LOAD_UNLOAD_FLOW_CST_RECV_DONE_DONE_CHECK,
#pragma endregion

		_ePAPER_LOAD_UNLOAD_FLOW_DONE,
	};
};

