#pragma once

class CReadyFlow : public CBaseFlow
{
public:
	CReadyFlow();
	~CReadyFlow();

private:
	BOOL			m_FlowFinish;

	void(*m_StateComplete)(void *pArgument);

	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);

public:
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;

	BOOL InitProcess();
	BOOL EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start();
	BOOL			Stop();

	enum eReadyFlow
	{
		_eREADY_FLOW_ERROR = -1,

		_eREADY_FLOW_IDLE = 0,
		_eREADY_FLOW_START,

#pragma region //All Ready
		_eREADY_FLOW_INTERLOCK_CHECK,

		_eREADY_FLOW_BOX_ALIGN_CAMERA_Y_WAIT_POS,
		_eREADY_FLOW_BOX_ALIGN_CAMERA_Y_WAIT_POS_CHECK,

		_eREADY_FLOW_UNLOADER_VAC_OFF,
		_eREADY_FLOW_UNLOADER_VAC_OFF_CHECK,
		_eREADY_FLOW_UNLOADER_Z_UP,
		_eREADY_FLOW_UNLOADER_Z_UP_CHECK,
		_eREADY_FLOW_UNLOADER_Y_WAIT_POS,  //(YL축으로 움직인다. Program 실행시 항상 YL Master로 설정해주는 코드 추가 필요)
		_eREADY_FLOW_UNLOADER_Y_WAIT_POS_CHECK,

		_eREADY_FLOW_LOADER_VAC_OFF,
		_eREADY_FLOW_LOADER_VAC_OFF_CHECK,
		_eREADY_FLOW_LOADER_BLOW_ON,
		_eREADY_FLOW_LOADER_BLOW_ON_CHECK, //On Check 필요한지 확인
		_eREADY_FLOW_LOADER_BLOW_OFF,
		_eREADY_FLOW_LOADER_BLOW_OFF_CHECK,
		_eREADY_FLOW_LOADER_CYLINDER_UP,
		_eREADY_FLOW_LOADER_CYLINDER_UP_CHECK,
		_eREADY_FLOW_LOADER_Z_UP,
		_eREADY_FLOW_LOADER_Z_UP_CHECK,

		_eREADY_FLOW_GANTRY_Z_ALL_WAIT_POS,
		_eREADY_FLOW_GANTRY_Z_ALL_WAIT_POS_CHECK,
		_eREADY_FLOW_GANTRY_XY_WAIT_POS,
		_eREADY_FLOW_GANTRY_XY_WAIT_POS_CHECK,

		_eREADY_FLOW_GRIPPER_CLAMP_OFF,
		_eREADY_FLOW_GRIPPER_CLAMP_OFF_CHECK,
		_eREADY_FLOW_GRIPPER_Z_WAIT_POS,
		_eREADY_FLOW_GRIPPER_Z_WAIT_POS_CHECK,
		_eREADY_FLOW_GRIPPER_STRETCH_WAIT_POS,
		_eREADY_FLOW_GRIPPER_STRETCH_WAIT_POS_CHECK,
		_eREADY_FLOW_GRIPPER_PITCH_WAIT_POS,
		_eREADY_FLOW_GRIPPER_PITCH_WAIT_POS_CHECK,
		_eREADY_FLOW_LOADING_STAGE_UVW_WAIT_POS,
		_eREADY_FLOW_LOADING_STAGE_UVW_WAIT_POS_CHECK,
#pragma endregion

		_eREADY_FLOW_DONE,
	};
};

