#pragma once

class CStickPaperUnloadFlow : public CBaseFlow
{
public:
	CStickPaperUnloadFlow();
	~CStickPaperUnloadFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start();
	BOOL			Stop();

	double			m_dTargetPosZ;
	double			m_dTargetPosZL, m_dTargetPosZR;
	double			m_dTargetPosX;
	double			m_dTargetPosXL, m_dTargetPosXR;

	int				m_nGroupStepIndex; //KJT 20210221
	BOOL			m_bGroupStepDone[200]; //KJT 20210221

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	CTime			m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	double			m_dCurPos, m_dPrevPos;

	//[2]
	enum eStickPaperUnload //Junying TPCD
	{
		_eSTICK_PAPER_UNLOAD_FLOW_ERROR = -1,

		_eSTICK_PAPER_UNLOAD_FLOW_IDLE = 0,
		_eSTICK_PAPER_UNLOAD_FLOW_START,
		_eSTICK_PAPER_UNLOAD_FLOW_INTERLOCK, //INSPECTION STAGE VAC OFF 스틱 유무 체크.있으면 ERROR

		_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Y_UNLOAD_START,
		_eSTICK_PAPER_UNLOAD_FLOW_LOADER_Y_UNLOAD_UNLOAD_START,
		_eSTICK_PAPER_UNLOAD_FLOW_STICK_PAPER_UNLOAD_DONE_CHECK,
		_eSTICK_PAPER_UNLOAD_FLOW_UNLOAD_DONE_CHECK,

		_eSTICK_PAPER_UNLOAD_FLOW_DONE,
	};
};

#if 0 //Move Reserve
#pragma region //2. PaperUnloader PickUp In Box
//_eSTICK_PAPER_UNLOAD_FLOW_GANTRY_Y_PAPER_UNLOAD_POS,
//_eSTICK_PAPER_UNLOAD_FLOW_GANTRY_Y_PAPER_UNLOAD_POS_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_POS_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS_CHECK,

_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_VAC_ON,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_UP,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_STEP_UP_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS_CHECK,

_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS_CHECK,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS,
_eSTICK_PAPER_UNLOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS_CHECK,
#pragma endregion //2. PaperUnloader PickUp In Box
#endif