#pragma once

class CStickPaperLoadFlow : public CBaseFlow
{
public:
	CStickPaperLoadFlow();
	~CStickPaperLoadFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start();
	BOOL			Stop();

	double			m_dTargetPosZ_Loader, m_dTargetPosZ_PaperUnloader;
	double			m_dTargetPosZL, m_dTargetPosZR;
	double			m_dTargetPosX;
	double			m_dTargetPosXL, m_dTargetPosXR;

	int				m_nGroupStepIndex; //KJT 20210221
	BOOL			m_bGroupStepDone[200]; //KJT 20210221

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	CTime			m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	double			m_dCurPos, m_dPrevPos;

	//[2]
	enum eStickPaperLoad //Junying TPCD
	{
		_eSTICK_PAPER_LOAD_FLOW_ERROR = -1,

		_eSTICK_PAPER_LOAD_FLOW_IDLE = 0,
		_eSTICK_PAPER_LOAD_FLOW_START,
		_eSTICK_PAPER_LOAD_FLOW_INTERLOCK, //INSPECTION STAGE VAC OFF 스틱 유무 체크.있으면 ERROR

#pragma region //Unloader Ready
		_eSTICK_PAPER_LOAD_FLOW_UNLOADER_READY,
		_eSTICK_PAPER_LOAD_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry ZX Ready
		_eSTICK_PAPER_LOAD_FLOW_GANTRY_ZX_READY,
		_eSTICK_PAPER_LOAD_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_eSTICK_PAPER_LOAD_FLOW_LOADER_READY,
		_eSTICK_PAPER_LOAD_FLOW_LOADER_READY_CHECK,
#pragma endregion

#pragma region //PaperUnloaderZX Ready
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_ZX_READY,
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_ZX_READY_CHECK,
#pragma endregion

#pragma region //1. Loader Pickup In Box
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Y_LOAD_IN_BOX_POS,  //1
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Y_LOAD_IN_BOX_POS_CHECK, //6
		_eSTICK_PAPER_LOAD_FLOW_LOADER_X_LOAD_IN_BOX_POS, //7
		_eSTICK_PAPER_LOAD_FLOW_LOADER_X_LOAD_IN_BOX_POS_CHECK, //8
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS, //10
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS_CHECK, //15
		_eSTICK_PAPER_LOAD_FLOW_LOADER_VAC_ON, //16
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN, //17
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN_CHECK, //18
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_STEP_UP, //KJT 20210316
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_STEP_UP_CHECK,
		//_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_POS, //KJT 20210317
		//_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_POS_CHECK,
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_UP_POS, //KJT 20210317
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_UP_POS_CHECK,
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_DOWN_POS, //KJT 20210317
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_VIBRATION_DOWN_POS_CHECK,

		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS, //19
		_eSTICK_PAPER_LOAD_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS_CHECK, //20
		_eSTICK_PAPER_LOAD_FLOW_LOADER_X_TENSION_POS, //21
		_eSTICK_PAPER_LOAD_FLOW_LOADER_X_TENSION_POS_CHECK, //22
#pragma endregion //1. Loader Pickup In Box

#pragma region //2. Paper PickUp In Box
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_IN_BOX_POS, //2
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_IN_BOX_POS_CHECK, //3
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS, //4
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS_CHECK, //5
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS, //9
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS_CHECK, //11
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_VAC_ON, //12
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN, //13
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN_CHECK, //14
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP, //23
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STICK_LOAD_STEP_UP_CHECK, //24
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS, //25
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS_CHECK, //26
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS, //27
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS_CHECK, //28
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS, //29
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS_CHECK, //30
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS, //31
		_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS_CHECK, //32
#pragma endregion //2. Paper PickUp In Box

		_eSTICK_PAPER_LOAD_FLOW_DONE,
	};
};

#if 0 //Move Reserve
#pragma region //2. PaperUnloader PickUp In Box
//_eSTICK_PAPER_LOAD_FLOW_GANTRY_Y_PAPER_UNLOAD_POS,
//_eSTICK_PAPER_LOAD_FLOW_GANTRY_Y_PAPER_UNLOAD_POS_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Y_PAPER_LOAD_POS_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_PAPER_LOAD_POS_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_PAPER_LOAD_DOWN_POS_CHECK,

_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_VAC_ON,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_DOWN_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_UP,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_STEP_UP_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_UP_POS_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_VIBRATION_DOWN_POS_CHECK,

_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_Z_WAIT_POS_CHECK,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS,
_eSTICK_PAPER_LOAD_FLOW_PAPER_UNLOADER_X_TENSION_POS_CHECK,
#pragma endregion //2. PaperUnloader PickUp In Box
#endif