#pragma once

class CStickClampTensionFlow : public CBaseFlow
{
public:
	CStickClampTensionFlow();
	~CStickClampTensionFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	enum eStickClampTensionFlow
	{
		_eSTICK_CLAMP_TENSION_FLOW_ERROR = -1,

		_eSTICK_CLAMP_TENSION_FLOW_IDLE = 0,
		_eSTICK_CLAMP_TENSION_FLOW_START,
		_eSTICK_CLAMP_TENSION_FLOW_INTERLOCK,

#pragma region //Unloader Ready
		_eSTICK_CLAMP_TENSION_FLOW_UNLOADER_READY,
		_eSTICK_CLAMP_TENSION_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry ZX Ready
		_eSTICK_CLAMP_TENSION_FLOW_GANTRY_ZX_READY,
		_eSTICK_CLAMP_TENSION_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_eSTICK_CLAMP_TENSION_FLOW_LOADER_READY,
		_eSTICK_CLAMP_TENSION_FLOW_LOADER_READY_CHECK,
#pragma endregion

#pragma region //PaperUnloaderZXY Ready
		_eSTICK_CLAMP_TENSION_FLOW_PAPER_UNLOADER_ZXY_READY,
		_eSTICK_CLAMP_TENSION_FLOW_PAPER_UNLOADER_ZXY_READY_CHECK,
#pragma endregion

		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_CLAMP_OFF,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_CLAMP_OFF_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_BWD_POS,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_BWD_POS_CHECK,
		//_eSTICK_CLAMP_TENSION_FLOW_PITCH_WORK_POS,
		//_eSTICK_CLAMP_TENSION_FLOW_PITCH_WORK_POS_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_LOAD_POS,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_LOAD_POS_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_FWD_POS,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_FWD_POS_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_UP_CLAMP_POS,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_UP_CLAMP_POS_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_CLAMP_ON,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_CLAMP_ON_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_INSPECTION_STAGE_VAC_OFF,
		_eSTICK_CLAMP_TENSION_FLOW_INSPECTION_STAGE_VAC_OFF_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_TENSION_POS,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_TENSION_POS_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_FORCE_ZERO,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_FORCE_ZERO_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_SET_PARA,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_TENSION_START,
		_eSTICK_CLAMP_TENSION_FLOW_STRETCH_TENSION_CHECK,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_DOWN_CLAMP_POS,
		_eSTICK_CLAMP_TENSION_FLOW_GRIPPER_Z_DOWN_CLAMP_POS_CHECK,

		_eSTICK_CLAMP_TENSION_FLOW_DONE,
	};
};

