#pragma once
class CStickLoadInStageToBoxFlow : public CBaseFlow
{
public:
	CStickLoadInStageToBoxFlow();
	~CStickLoadInStageToBoxFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	double			m_dTargetPosZ;

	BOOL			FlowInterlock();

	//[2]
	enum eStickLoadInStageToBox
	{
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_ERROR = -1,

		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_IDLE = 0,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_START,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_INTERLOCK, //INSPECTION STAGE VAC OFF 스틱 유무 체크.있으면 ERROR

#pragma region //Unloader Ready
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_UNLOADER_READY,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry Z,X Ready
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_ZX_READY,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_READY,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_READY_CHECK,
#pragma endregion

#pragma region //Gripper Ready
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GRIPPER_READY,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GRIPPER_READY_CHECK,
#pragma endregion

#pragma region //Inspection Uvw Ready
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_INSPECTION_UVW_STICK_LOAD_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_INSPECTION_UVW_STICK_LOAD_POS_CHECK,
#pragma endregion		
		
#pragma region //1. PickUp In Stage
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_STICK_LOAD_IN_STAGE_POS,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_STICK_LOAD_IN_STAGE_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Y_STICK_LOAD_IN_STAGE_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Y_STICK_LOAD_IN_STAGE_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_X_WAIT_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_X_WAIT_POS_CHECK,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_CYLINDER_UP,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_CYLINDER_UP_CHECK,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_SUB_Z_UP,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_SUB_Z_UP_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_VAC_ON,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_VAC_ON_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_INSPECTION_STAGE_VAC_OFF,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_INSPECTION_STAGE_VAC_OFF_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS_CHECK,
#pragma endregion //1. PickUp In Stage

#pragma region //2. Unload To Inspection Box
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_STICK_UNLOAD_TO_BOX_POS,
		//_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_STICK_UNLOAD_TO_BOX_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Y_STICK_UNLOAD_TO_BOX_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Y_STICK_UNLOAD_TO_BOX_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_UNLOAD_DOWN_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_UNLOAD_DOWN_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_UNLOAD_VAC_OFF,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_STICK_UNLOAD_VAC_OFF_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_FINISH_WAIT_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_LOADER_Z_FINISH_WAIT_POS_CHECK,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_WAIT_POS,
		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_GANTRY_Y_WAIT_POS_CHECK,
#pragma endregion //2. Unload To Inspection Box

		_eSTICK_LOAD_IN_STAGE_TO_BOX_FLOW_DONE,
	};
};

