#pragma once
class CStickClampTensionUnclampFlow : public CBaseFlow
{
public:
	CStickClampTensionUnclampFlow();
	~CStickClampTensionUnclampFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	//Clamp + 1Tension + Unclamp
	enum eStickClampTensionUnclampFlow
	{
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_ERROR = -1,

		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_IDLE = 0,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_START,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_INTERLOCK,

		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_CLAMP_TENSION_START,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_CLAMP_TENSION_DONE_CHECK,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_GRIPPER_Z_DOWN_CLAMP_POS,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_GRIPPER_Z_DOWN_CLAMP_POS_CHECK,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_ON,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_ON_CHECK,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_STRETCH_SET_RELEASE_PARA,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_STRETCH_RELEASE_START,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_STRETCH_RELEASE_CHECK,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_GRIPPER_CLAMP_OFF,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_GRIPPER_CLAMP_OFF_CHECK,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_STRETCH_BWD_POS,
		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_STRETCH_BWD_POS_CHECK,

		_eSTICK_CLAMP_TENSION_UNCLAMP_FLOW_DONE,
	};
};

