#pragma once

class CStickReleaseUnclampFlow : public CBaseFlow
{
public:
	CStickReleaseUnclampFlow();
	~CStickReleaseUnclampFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	enum eStickRelaeseUnclampFlow
	{
		_eSTICK_RELEASE_UNCLAMP_FLOW_ERROR = -1,

		_eSTICK_RELEASE_UNCLAMP_FLOW_IDLE = 0,
		_eSTICK_RELEASE_UNCLAMP_FLOW_START,
		_eSTICK_RELEASE_UNCLAMP_FLOW_INTERLOCK,

#pragma region //Unloader Ready
		_eSTICK_RELEASE_UNCLAMP_FLOW_UNLOADER_READY,
		_eSTICK_RELEASE_UNCLAMP_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry ZX Ready
		_eSTICK_RELEASE_UNCLAMP_FLOW_GANTRY_ZX_READY,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader Ready
		_eSTICK_RELEASE_UNCLAMP_FLOW_LOADER_READY,
		_eSTICK_RELEASE_UNCLAMP_FLOW_LOADER_READY_CHECK,
#pragma endregion

//#pragma region //Box Camera Ready
//		_eSTICK_RELEASE_UNCLAMP_FLOW_BOX_CAMERA_READY,
//		_eSTICK_RELEASE_UNCLAMP_FLOW_BOX_CAMERA_READY_CHECK,
//#pragma endregion

#pragma region //PaperUnloaderZXY Ready
		_eSTICK_RELEASE_UNCLAMP_FLOW_PAPER_UNLOADER_ZXY_READY,
		_eSTICK_RELEASE_UNCLAMP_FLOW_PAPER_UNLOADER_ZXY_READY_CHECK,
#pragma endregion

		_eSTICK_RELEASE_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_OFF,
		_eSTICK_RELEASE_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_OFF_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_Z_TENSION_POS,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_Z_TENSION_POS_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_STRETCH_SET_RELEASE_PARA,
		_eSTICK_RELEASE_UNCLAMP_FLOW_STRETCH_RELEASE_START,
		_eSTICK_RELEASE_UNCLAMP_FLOW_STRETCH_RELEASE_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_Z_CLAMP_POS,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_Z_CLAMP_POS_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_ON,
		_eSTICK_RELEASE_UNCLAMP_FLOW_INSPECTION_STAGE_VAC_ON_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_CLAMP_OFF,
		_eSTICK_RELEASE_UNCLAMP_FLOW_GRIPPER_CLAMP_OFF_CHECK,
		_eSTICK_RELEASE_UNCLAMP_FLOW_STRETCH_BWD_POS,
		_eSTICK_RELEASE_UNCLAMP_FLOW_STRETCH_BWD_POS_CHECK,

		_eSTICK_RELEASE_UNCLAMP_FLOW_DONE,
	};
};

