#pragma once

class CStickUnloadInStageToCstFlow : public CBaseFlow
{
public:
	CStickUnloadInStageToCstFlow();
	~CStickUnloadInStageToCstFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start();
	BOOL			Stop();

	CTime m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	double			GetCSTTargetSlotPos();

	double			m_dTargetPosZ;
	double			m_dTargetPosUldX;
	double			m_dTargetPosUldY;

	enum_CassetteFloor m_eTargetFloor = eCASSETTE_FLOOR_1;
	//enum_CassetteSlot m_eTargetSlot;

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	enum eStickUnloadInStageToCstFlow
	{
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_ERROR = -1,

		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_IDLE = 0,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_START,

		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_INTERLOCK,

#pragma region //Unloader Ready
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_READY,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry ZX Ready
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_GANTRY_ZX_READY,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_GANTRY_ZX_READY_CHECK,
#pragma endregion

#pragma region //Loader ZXY Ready
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_LOADER_ZXY_READY,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_LOADER_ZXY_READY_CHECK,
#pragma endregion

#pragma region //PaperUnloaderZX Ready
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_PAPER_UNLOADER_ZX_READY,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_PAPER_UNLOADER_ZX_READY_CHECK,
#pragma endregion

		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Y_STICK_LOAD_IN_STAGE_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Y_STICK_LOAD_IN_STAGE_POS_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_STICK_LOAD_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_STICK_LOAD_POS_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_STICK_LOAD_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_STICK_LOAD_POS_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_VAC_ON,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_VAC_ON_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_INSP_STAGE_VAC_OFF,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_INSP_STAGE_VAC_OFF_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_WAIT_POS_2ND,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_WAIT_POS_2ND_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_TENSION_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_TENSION_POS_CHECK,

#pragma region //4. Stick Unload To Cst
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Y_UNLOAD_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Y_UNLOAD_POS_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_UNLOAD_POS,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_UNLOAD_POS_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_VAC_OFF_2ND,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_VAC_OFF_2ND_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_WAIT_POS_FINISH,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_Z_WAIT_POS_FINISH_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_WAIT_POS_2ND,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_UNLOADER_X_WAIT_POS_2ND_CHECK,
#pragma endregion 

#pragma region //Cst Move
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_CST_RECV_READY_MOVE,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_CST_RECV_READY_DONE_CHECK,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_CST_RECV_DONE_MOVE,
		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_CST_RECV_DONE_DONE_CHECK,
#pragma endregion 

		_eSTICK_UNLOAD_IN_STAGE_TO_CST_FLOW_DONE,

		
	//	[7. STICK UNLOAD]
	//BOX CAMERA Y WAIT POS(CYD CHECK) 항상 일단 WAIT POS 간다

	//	UNLOADER VAC OFF
	//	BLOW ON
	//	BLOW OFF
	//	UNLOADER CYD UP
	//	UNLOADER Z UP
	//	UNLOADER Y WAIT

	//	LOADER VAC OFF
	//	BLOW ON
	//	BLOW OFF
	//	LOADER CYD UP
	//	LOADER Z UP

	//	CAMERA Z ALL UP
	//	GANTRY XY WAIT

	//	CLAMP OFF
	//	GRIPPER UP
	//	STRETCH WAIT
	//	PITCH WAIT

	//	//
	//	GANTRY XY WAIT POS(UNLOADER와 간섭이 없어야한다)

	//	UNLAODER Y STICK LOAD POS
	//	UNLOADER Z STICK LOAD1 POS(10mm 위, Offset Optrion)
	//	UNLOADER CYD DOWN
	//	UNLOADER Z STICK LOAD2 POS
	//	UNLOADER VAC ON
	//	INSPECTION STAGE VAC OFF
	//	INSPECTION STAGE BLOW ON
	//	INSPECTION STAGE BLOW OFF
	//	UNLOADER CYD UP
	//	UNLOADER Z UP
	};
};

