#pragma once

class CStickLoadInBoxToStageFlow : public CBaseFlow
{
public:
	CStickLoadInBoxToStageFlow();
	~CStickLoadInBoxToStageFlow();

private:
	CWinThread*		pThread;
	VOID			ThreadFunctionEntry(VOID);
	static UINT		ThreadFunction(LPVOID lpParam);
	BOOL			m_FlowFinish;
	BOOL			m_bFlowDone;
	BOOL			m_bStopBit;
	void(*m_StateComplete)(void *pArgument);

public:
	BOOL			InitProcess();
	BOOL			EndProcess();

	HANDLE			hHandle;
	BOOL			m_bTerminate;
	BOOL			IsTerminate() { return m_bTerminate; }
	BOOL			IsFlowDone() { return m_bFlowDone; }

	BOOL			Start(int nStep);
	BOOL			Stop();

	double			m_dTargetPosZ;
	double			m_dTargetPosX;

	int				m_nGroupStepIndex; //KJT 20210221
	BOOL			m_bGroupStepDone[200]; //KJT 20210221

	int             m_nMaxStepDownCount;
	int				m_nMaxVibrationCount; //KJT 20210317
	int             m_nStepDownCount;
	int				m_nVibrationCount; //KJT 20210317

	CTime			m_timeStart; //KJT 20210329

	BOOL			FlowInterlock();

	//[2]
	enum eStickLoadInBoxToStage
	{
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_ERROR = -1,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_IDLE = 0,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_START,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_INTERLOCK, //INSPECTION STAGE VAC OFF 스틱 유무 체크.있으면 ERROR

#pragma region //Unloader Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_UNLOADER_READY,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_UNLOADER_READY_CHECK,
#pragma endregion

#pragma region //Gantry ZXY Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_GANTRY_ZXY_READY,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_GANTRY_ZXY_READY_CHECK,
#pragma endregion

#pragma region //Loader ZX Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_ZX_READY,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_ZX_READY_CHECK,
#pragma endregion

#pragma region //PaperUnloader Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_PAPER_UNLOADER_ZXY_READY,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_PAPER_UNLOADER_ZXY_READY_CHECK,
#pragma endregion

#pragma region //Gripper Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_GRIPPER_READY,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_GRIPPER_READY_CHECK,
#pragma endregion

#pragma region //Inspection Uvw Ready
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_INSPECTION_UVW_STICK_LOAD_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_INSPECTION_UVW_STICK_LOAD_POS_CHECK,
#pragma endregion

#pragma region //1. Loader Pickup In Box
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_LOAD_IN_BOX_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_LOAD_IN_BOX_POS_CHECK,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_LOAD_IN_BOX_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_LOAD_IN_BOX_POS_CHECK,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_DOWN_POS_CHECK,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_VAC_ON,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_STEP_DOWN_CHECK,
		//_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_VAC_ON_CHECK,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_STEP_UP, //KJT 20210316
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_STEP_UP_CHECK,
		//_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_POS, //KJT 20210317
		//_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_UP_POS, //KJT 20210317
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_UP_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_DOWN_POS, //KJT 20210317
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_VIBRATION_DOWN_POS_CHECK,

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_LOAD_WAIT_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_TENSION_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_TENSION_POS_CHECK,
#pragma endregion //1. PickUp In Box

#pragma region //2. Unload To Inspection Stage
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_STICK_UNLOAD_TO_INSPECTION_STAGE_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_STICK_UNLOAD_TO_INSPECTION_STAGE_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_UNLOAD_DOWN_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_STICK_UNLOAD_DOWN_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_INSPECTION_STAGE_VAC_ON,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_INSPECTION_STAGE_VAC_ON_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_VAC_OFF,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_VAC_OFF_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_FINISH_WAIT_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Z_FINISH_WAIT_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_FINISH_WAIT_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_X_FINISH_WAIT_POS_CHECK,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_FINISH_WAIT_POS,
		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_LOADER_Y_FINISH_WAIT_POS_CHECK,
#pragma endregion //2. Unload To Inspection Stage

		_eSTICK_LOAD_IN_BOX_TO_STAGE_FLOW_DONE,
	};
};

