#pragma once


#ifndef ULTRA_RETURN_VALUE_DEF
#define ULTRA_RETURN_VALUE_DEF
typedef enum
{
	RET_SUCCESS,

	COMM_ERROR_SIZE,
	COMM_ERROR_LRC,
	COMM_ERROR_TRANSACTION_ID,
	COMM_ERROR_PROTOCOL_ID,
	COMM_ERROR_UNIT_ID,
	COMM_ERROR_FC,
	COMM_FUNCTION_ADDR,

	MOTION_NOT_HOMING,
	MOTION_SERVO_OFF,
	MOTION_IS_ALARM,
	MOTION_IS_BUSY,
	MOTION_IS_P_LIMIT,
	MOTION_IS_N_LIMIT,

	STRETCH_STEP_COUNT,
	STRETCH_IS_RUNNING,
	CLAMP_IS_RUNNING,
	FORCE_CONTROL_RUNNING,

	GANTRY_COM_FAIL,

	VISION_FIND_FAIL,

	LIGHT_CONTROL_FAIL = 21,


	MAX_RETURN_VALUE,
}enum_ULTRA_RETURN_VALUE;
#endif